In [126]:
import pandas as pd
import numpy as np

In [127]:
df1 = pd.read_csv('booking.csv')
df1

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
0,INN00001,1,1,2,5,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,88.00,0,10/2/2015,Not_Canceled
1,INN00002,1,0,1,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,11/6/2018,Not_Canceled
2,INN00003,2,1,1,3,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,50.00,0,2/28/2018,Canceled
3,INN00004,1,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,1,5/20/2017,Canceled
4,INN00005,1,0,1,2,Not Selected,0,Room_Type 1,48,Online,0,0,0,77.00,0,4/11/2018,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36280,INN36282,2,0,0,2,Meal Plan 2,0,Room_Type 1,346,Online,0,0,0,115.00,1,9/13/2018,Canceled
36281,INN36283,2,0,1,3,Meal Plan 1,0,Room_Type 1,34,Online,0,0,0,107.55,1,10/15/2017,Not_Canceled
36282,INN36284,2,0,1,3,Meal Plan 1,0,Room_Type 4,83,Online,0,0,0,105.61,1,12/26/2018,Not_Canceled
36283,INN36285,3,0,0,4,Meal Plan 1,0,Room_Type 1,121,Offline,0,0,0,96.90,1,7/6/2018,Not_Canceled
36284,INN36286,2,0,0,5,Meal Plan 1,0,Room_Type 4,44,Online,0,0,0,133.44,3,10/18/2018,Not_Canceled

In [128]:
df1.shape

(36285, 17)

In [129]:
df1.columns

Index(['Booking_ID', 'number of adults', 'number of children',
       'number of weekend nights', 'number of week nights', 'type of meal',
       'car parking space', 'room type', 'lead time', 'market segment type',
       'repeated', 'P-C', 'P-not-C', 'average price', 'special requests',
       'date of reservation', 'booking status'],
      dtype='object')

In [130]:
df1["date of reservation"]=pd.to_datetime(df1["date of reservation"], errors='coerce', dayfirst=True)
df1["arrival_year"]=df1["date of reservation"].dt.year
df1['arrival_month']=df1["date of reservation"].dt.month
df1['arrival_month_name']=df1['date of reservation'].dt.month_name()
df1['arrival_week_no']=df1['date of reservation'].dt.isocalendar().week

In [131]:
df1=df1.rename(columns={
    'number of adults':'Adults',
    'number of children':'Children',
})
df1['Babies']=0

In [132]:

df1=df1.rename(columns={
    'room type':'room_type_reserved',
    'market segment':'market_segment_type',
    'average price':'avg_price_per_room',
    'number of weekend nights':'weekend nights',
    'number of week nights':'week nights',
    'market segment type':'market_segment'
})

In [133]:
df1['distribution_channel']=0
df1['extra_charges']=0
df1['discount']=0
df1['customer_type']=0
df1['Net_revenue']=0

In [134]:
df1.drop(columns=['Booking_ID','repeated','P-C','P-not-C','car parking space'],inplace=True,errors='ignore')

In [135]:
df1.drop(columns=['type of meal','special requests','date of reservation'],inplace=True,errors='ignore')

In [136]:
df1.columns

Index(['Adults', 'Children', 'weekend nights', 'week nights',
       'room_type_reserved', 'lead time', 'market_segment',
       'avg_price_per_room', 'booking status', 'arrival_year', 'arrival_month',
       'arrival_month_name', 'arrival_week_no', 'Babies',
       'distribution_channel', 'extra_charges', 'discount', 'customer_type',
       'Net_revenue'],
      dtype='object')

In [137]:
df1.head()

,Adults,Children,weekend nights,week nights,room_type_reserved,lead time,market_segment,avg_price_per_room,booking status,arrival_year,arrival_month,arrival_month_name,arrival_week_no,Babies,distribution_channel,extra_charges,discount,customer_type,Net_revenue
0,1,1,2,5,Room_Type 1,224,Offline,88.00,Not_Canceled,2015.0,2.0,February,7,0,0,0,0,0,0
1,1,0,1,3,Room_Type 1,5,Online,106.68,Not_Canceled,2018.0,6.0,June,24,0,0,0,0,0,0
2,2,1,1,3,Room_Type 1,1,Online,50.00,Canceled,NaN,NaN,NaN,<NA>,0,0,0,0,0,0
3,1,0,0,2,Room_Type 1,211,Online,100.00,Canceled,NaN,NaN,NaN,<NA>,0,0,0,0,0,0
4,1,0,1,2,Room_Type 1,48,Online,77.00,Canceled,2018.0,11.0,November,44,0,0,0,0,0,0

In [138]:
df2=pd.read_csv('hotel_bookings.csv')
df2

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [139]:
df2.drop(columns=['hotel','arrival_date_day_of_month','is_canceled','meal','country','is_repeated_guest','previous_cancellations','previous_bookings_not_canceled','assigned_room_type','booking_changes','deposit_type','agent','company','days_in_waiting_list','adr','total_of_special_requests','reservation_status_date','required_car_parking_spaces'], inplace=True,errors='ignore')

In [140]:
df2=df2.rename(columns={
    'market_segment':'market_segment_type',
    'arrival_date_year':'arrival_year',
    'arrival_date_month':'arrival_month',
    'arrival_date_week_number':'arrival_week_no',
    'reservation_status':'room_type_reserved',
    'stays_in_weekend_nights':'weekend nights',
    'stays_in_week_nights':'week nights',
    'market_segment_type':'market_segment',
   'reserved_room_type':'room_type_reserved',
   'adults':'Adults',
   'children':'Children',
   'babies':'Babies'
    
})

In [141]:
df2['avg_price_per_room']=0
df2['extra_charges']=0
df2['discount']=0
df2['Net_revenue']=0
df2['booking_status']=0

In [142]:
df2.columns

Index(['lead_time', 'arrival_year', 'arrival_month', 'arrival_week_no',
       'weekend nights', 'week nights', 'Adults', 'Children', 'Babies',
       'market_segment_type', 'distribution_channel', 'room_type_reserved',
       'customer_type', 'room_type_reserved', 'avg_price_per_room',
       'extra_charges', 'discount', 'Net_revenue', 'booking_status'],
      dtype='object')

In [143]:
df2.head()

,lead_time,arrival_year,arrival_month,arrival_week_no,weekend nights,week nights,Adults,Children,Babies,market_segment_type,distribution_channel,room_type_reserved,customer_type,room_type_reserved,avg_price_per_room,extra_charges,discount,Net_revenue,booking_status
0,342,2015,July,27,0,0,2,0.0,0,Direct,Direct,C,Transient,Check-Out,0,0,0,0,0
1,737,2015,July,27,0,0,2,0.0,0,Direct,Direct,C,Transient,Check-Out,0,0,0,0,0
2,7,2015,July,27,0,1,1,0.0,0,Direct,Direct,A,Transient,Check-Out,0,0,0,0,0
3,13,2015,July,27,0,1,1,0.0,0,Corporate,Corporate,A,Transient,Check-Out,0,0,0,0,0
4,14,2015,July,27,0,2,2,0.0,0,Online TA,TA/TO,A,Transient,Check-Out,0,0,0,0,0

In [144]:
df3=pd.read_csv('Hotel_Reservations.csv')
df3

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36270,INN36271,3,0,2,6,Meal Plan 1,0,Room_Type 4,85,2018,8,3,Online,0,0,0,167.80,1,Not_Canceled
36271,INN36272,2,0,1,3,Meal Plan 1,0,Room_Type 1,228,2018,10,17,Online,0,0,0,90.95,2,Canceled
36272,INN36273,2,0,2,6,Meal Plan 1,0,Room_Type 1,148,2018,7,1,Online,0,0,0,98.39,2,Not_Canceled
36273,INN36274,2,0,0,3,Not Selected,0,Room_Type 1,63,2018,4,21,Online,0,0,0,94.50,0,Canceled
36274,INN36275,2,0,1,2,Meal Plan 1,0,Room_Type 1,207,2018,12,30,Offline,0,0,0,161.67,0,Not_Canceled

In [145]:
df3=df3.rename(columns={
    'no_of_adults':'Adults',
    'no_of_children':'Children',
    'no_of_week_nights':'week_nights',
    'no_of_weekend_nights':'weekend_nights',
    'market_segment_type':'market_segment',
    'reserved_room_type':'room_type_reserved'
})

In [146]:
df3.drop(columns=['Booking_ID','type_of_meal_plan','required_car_parking_space','repeated_guest','no_of_previous_cancellations','no_of_previous_bookings_not_canceled','arrival_date','no_of_special_requests'],inplace=True,errors='ignore')

In [147]:
df3['booking_status']=0
df3['avg_price_per_room']=0
df3['extra_charges']=0
df3['discount']=0
df3['Babies']=0
df3['distribution_chaannel']=0
df3['arrival_week_number']=0
df3['customer_type']=0
df3['Net_revenue']=0

In [148]:
df3.columns

Index(['Adults', 'Children', 'weekend_nights', 'week_nights',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'market_segment', 'avg_price_per_room', 'booking_status',
       'extra_charges', 'discount', 'Babies', 'distribution_chaannel',
       'arrival_week_number', 'customer_type', 'Net_revenue'],
      dtype='object')

In [149]:
df3.head()

,Adults,Children,weekend_nights,week_nights,room_type_reserved,lead_time,arrival_year,arrival_month,market_segment,avg_price_per_room,booking_status,extra_charges,discount,Babies,distribution_chaannel,arrival_week_number,customer_type,Net_revenue
0,2,0,1,2,Room_Type 1,224,2017,10,Offline,0,0,0,0,0,0,0,0,0
1,2,0,2,3,Room_Type 1,5,2018,11,Online,0,0,0,0,0,0,0,0,0
2,1,0,2,1,Room_Type 1,1,2018,2,Online,0,0,0,0,0,0,0,0,0
3,2,0,0,2,Room_Type 1,211,2018,5,Online,0,0,0,0,0,0,0,0,0
4,2,0,1,1,Room_Type 1,48,2018,4,Online,0,0,0,0,0,0,0,0,0

In [150]:
df4=pd.read_csv('ITC_Hotels.csv')
df4

,Booking_ID,Hotel_Name,Hotel_Category,City,State,Country,Checkin_Date,Checkout_Date,Month,Quarter,...,Net_Revenue,GST_Amount,Total_With_GST,Booking_Channel,Customer_Type,Payment_Mode,Occupancy_Status,Customer_Rating,Feedback_Status,Covid_Impact_Level
0,BK9835534,ITC Kakatiya,Luxury,Hyderabad,Telangana,India,44320,44324,May,Q2,...,89160,10699.20,99859.20,Walk-in,Regular,UPI,Checked-Out,4.6,Positive,High
1,BK7803377,ITC Royal Bengal,Luxury,Kolkata,West Bengal,India,44352,44356,June,Q2,...,86830,10419.60,97249.60,Corporate,VIP,Credit Card,Checked-In,4.6,Positive,High
2,BK3686278,ITC Grand Goa,Resort,Goa,Goa,India,44443,44445,September,Q3,...,29389,3526.68,32915.68,Booking.com,Corporate,Cash,Checked-In,4.2,Positive,Low
3,BK7514886,Fortune Select Trinity,Business,Bengaluru,Karnataka,India,44469,44470,September,Q3,...,24409,2929.08,27338.08,Website,Regular,Debit Card,Cancelled,3.8,Neutral,Low
4,BK6312815,ITC Narmada,Business,Ahmedabad,Gujarat,India,44461,44463,September,Q3,...,9940,1192.80,11132.80,Walk-in,New Guest,UPI,Checked-In,4.6,Negative,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299995,BK9563669,ITC Grand Goa,Resort,Goa,Goa,India,44546,44549,December,Q4,...,71558,8586.96,80144.96,Booking.com,New Guest,Cash,Checked-In,3.2,Negative,Low
299996,BK1707783,Welcomhotel Dwarka,Business,New Delhi,Delhi,India,44506,44509,November,Q4,...,13783,1653.96,15436.96,Booking.com,New Guest,UPI,Checked-Out,4.7,Positive,Low
299997,BK9144694,ITC Narmada,Business,Ahmedabad,Gujarat,India,44584,44589,January,Q1,...,133883,16065.96,149948.96,Website,Regular,Credit Card,Checked-In,3.4,Positive,High
299998,BK8123173,ITC Windsor,Business,Bengaluru,Karnataka,India,44421,44424,August,Q3,...,38941,4672.92,43613.92,Website,Corporate,Credit Card,Checked-Out,4.2,Neutral,Low
299999,BK8351514,ITC Maratha,Luxury,Mumbai,Maharashtra,India,44376,44381,June,Q2,...,34522,4142.64,38664.64,MakeMyTrip,Corporate,Debit Card,Checked-Out,4.9,Positive,High

In [151]:
df4.drop(columns=['Booking_ID','Hotel_Name','Hotel_Category','City','State','Country','Checkin_Date','Checkout_Date','Quarter','Gross_Revenue','GST_Amount','Total_With_GST','Booking_Channel','Payment_Mode','Occupancy_Status','Customer_Rating','Feedback_Status','Covid_Impact_Level'], inplace=True,errors='ignore')
df4.drop(columns=['Room_Type','Guests','Nights_Stayed','Room_Rate'], inplace=True,errors='ignore')

In [152]:
df4=df4.rename(columns={
    'Year':'arrivel_year',
    'Month':'arrival_month',
    
})

In [153]:
df4['arrival_week_number']=0
df4['lead_time']=0
df4['Adults']=0
df4['Children']=0
df4['Babies']=0
df4['Week_night']=0
df4['Weekend_nights']=0
df4['room_type_reserved']=0
df4['market_segment']=0
df4['distribution_channel']=0
df4['avg_price_per_room']=0
df4['extra_charges']=0
df4['booking_status']=0

In [154]:
df4.columns

Index(['arrival_month', 'arrivel_year', 'Extra_Charges', 'Discount',
       'Net_Revenue', 'Customer_Type', 'arrival_week_number', 'lead_time',
       'Adults', 'Children', 'Babies', 'Week_night', 'Weekend_nights',
       'room_type_reserved', 'market_segment', 'distribution_channel',
       'avg_price_per_room', 'extra_charges', 'booking_status'],
      dtype='object')

In [155]:
df4.head()

,arrival_month,arrivel_year,Extra_Charges,Discount,Net_Revenue,Customer_Type,arrival_week_number,lead_time,Adults,Children,Babies,Week_night,Weekend_nights,room_type_reserved,market_segment,distribution_channel,avg_price_per_room,extra_charges,booking_status
0,May,2021,2390,3506,89160,Regular,0,0,0,0,0,0,0,0,0,0,0,0,0
1,June,2021,4271,4213,86830,VIP,0,0,0,0,0,0,0,0,0,0,0,0,0
2,September,2021,4243,3802,29389,Corporate,0,0,0,0,0,0,0,0,0,0,0,0,0
3,September,2021,2363,3281,24409,Regular,0,0,0,0,0,0,0,0,0,0,0,0,0
4,September,2021,1092,4616,9940,New Guest,0,0,0,0,0,0,0,0,0,0,0,0,0

In [156]:
df1.columns

Index(['Adults', 'Children', 'weekend nights', 'week nights',
       'room_type_reserved', 'lead time', 'market_segment',
       'avg_price_per_room', 'booking status', 'arrival_year', 'arrival_month',
       'arrival_month_name', 'arrival_week_no', 'Babies',
       'distribution_channel', 'extra_charges', 'discount', 'customer_type',
       'Net_revenue'],
      dtype='object')

In [157]:
df2.columns

Index(['lead_time', 'arrival_year', 'arrival_month', 'arrival_week_no',
       'weekend nights', 'week nights', 'Adults', 'Children', 'Babies',
       'market_segment_type', 'distribution_channel', 'room_type_reserved',
       'customer_type', 'room_type_reserved', 'avg_price_per_room',
       'extra_charges', 'discount', 'Net_revenue', 'booking_status'],
      dtype='object')

In [158]:
df3.columns

Index(['Adults', 'Children', 'weekend_nights', 'week_nights',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'market_segment', 'avg_price_per_room', 'booking_status',
       'extra_charges', 'discount', 'Babies', 'distribution_chaannel',
       'arrival_week_number', 'customer_type', 'Net_revenue'],
      dtype='object')

In [159]:
df4.columns

Index(['arrival_month', 'arrivel_year', 'Extra_Charges', 'Discount',
       'Net_Revenue', 'Customer_Type', 'arrival_week_number', 'lead_time',
       'Adults', 'Children', 'Babies', 'Week_night', 'Weekend_nights',
       'room_type_reserved', 'market_segment', 'distribution_channel',
       'avg_price_per_room', 'extra_charges', 'booking_status'],
      dtype='object')

In [ ]:
df1=df1.loc[:,~df1.columns.duplicated()]
df2=df2.loc[:,~df2.columns.duplicated()]
df3=df3.loc[:,~df3.columns.duplicated()]
df4=df4.loc[:,~df4.columns.duplicated()]
#for removing duplicates

In [164]:
print("df1 duplicate:",df1.columns.duplicated().any())
print("df2 duplicate:",df2.columns.duplicated().any())
print("df3 duplicate:",df3.columns.duplicated().any())
print("df4 duplicate:",df4.columns.duplicated().any())

df1 duplicate: False
df2 duplicate: False
df3 duplicate: False
df4 duplicate: False

In [165]:
hotel_dataset=pd.concat([df1,df2,df3,df4])

In [166]:
hotel_dataset.shape

(491950, 33)

In [167]:
hotel_dataset.to_csv('hotel_dataset.csv',index=False)